// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.knowledge-base@1";
pub const DESCRIPTOR_VERSION: &str = "1.1.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const KNOWLEDGE_BASE_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const KNOWLEDGE_BASE_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_knowledge_base { () => { "{\"capability_id\":\"lenso.knowledge-base@1\",\"descriptor_version\":\"1.1.0\",\"operations\":[\"create_draft\",\"get_draft\",\"get_published_article\",\"list_articles\",\"publish_article\",\"search_published_articles\",\"update_draft\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_knowledge_base_client { () => { "{\"capability_id\":\"lenso.knowledge-base@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_knowledge_base_client { () => { "{\"capability_id\":\"lenso.knowledge-base@1\",\"descriptor_version\":\"1.1.0\",\"cardinality\":\"many\"}" }; }

pub const CREATE_DRAFT_OPERATION: &str = "create_draft";
pub const GET_DRAFT_OPERATION: &str = "get_draft";
pub const GET_PUBLISHED_ARTICLE_OPERATION: &str = "get_published_article";
pub const LIST_ARTICLES_OPERATION: &str = "list_articles";
pub const PUBLISH_ARTICLE_OPERATION: &str = "publish_article";
pub const SEARCH_PUBLISHED_ARTICLES_OPERATION: &str = "search_published_articles";
pub const UPDATE_DRAFT_OPERATION: &str = "update_draft";

pub use lenso_contract_runtime::{OptionalValue, Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateDraftRequest {
    #[serde(rename = "body_markdown")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub body_markdown: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "slug")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub slug: String,
    #[serde(rename = "title")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub title: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CreateDraftResponse {
    #[serde(rename = "article_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub article_id: String,
    #[serde(rename = "body_markdown")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub body_markdown: String,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: String,
    #[serde(rename = "created_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_by: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "slug")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub slug: String,
    #[serde(rename = "title")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub title: String,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum CreateDraftError {
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    SlugConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetDraftRequest {
    #[serde(rename = "article_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub article_id: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetDraftResponse {
    #[serde(rename = "article_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub article_id: String,
    #[serde(rename = "body_markdown")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub body_markdown: String,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "created_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_by: String,
    #[serde(rename = "latest_publication_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub latest_publication_revision: Option<String>,
    #[serde(rename = "latest_published_article_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub latest_published_article_revision: Option<String>,
    #[serde(rename = "latest_published_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub latest_published_at: Option<Timestamp>,
    #[serde(rename = "latest_published_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub latest_published_by: Option<String>,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "slug")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub slug: String,
    #[serde(rename = "title")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub title: String,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
    #[serde(rename = "updated_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_by: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum GetDraftError {
    ArticleNotFound,
    Forbidden,
    InvalidRequest,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetPublishedArticleRequest {
    #[serde(rename = "article_ref")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub article_ref: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct GetPublishedArticleResponse {
    #[serde(rename = "article_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub article_id: String,
    #[serde(rename = "article_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub article_revision: String,
    #[serde(rename = "body_markdown")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub body_markdown: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "publication_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub publication_revision: String,
    #[serde(rename = "published_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub published_at: String,
    #[serde(rename = "published_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub published_by: String,
    #[serde(rename = "slug")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub slug: String,
    #[serde(rename = "title")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub title: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum GetPublishedArticleError {
    ArticleNotFound,
    Forbidden,
    InvalidRequest,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListArticlesRequest {
    #[serde(rename = "cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub cursor: Option<String>,
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListArticlesResponse {
    #[serde(rename = "articles")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub articles: Vec<ListArticlesResponseArticlesItem>,
    #[serde(rename = "next_cursor")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub next_cursor: Option<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ListArticlesResponseArticlesItem {
    #[serde(rename = "article_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub article_id: String,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: Timestamp,
    #[serde(rename = "created_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_by: String,
    #[serde(rename = "latest_publication_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub latest_publication_revision: Option<String>,
    #[serde(rename = "latest_published_article_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub latest_published_article_revision: Option<String>,
    #[serde(rename = "latest_published_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub latest_published_at: Option<Timestamp>,
    #[serde(rename = "latest_published_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub latest_published_by: Option<String>,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "slug")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub slug: String,
    #[serde(rename = "title")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub title: String,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: Timestamp,
    #[serde(rename = "updated_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_by: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ListArticlesError {
    Forbidden,
    InvalidRequest,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PublishArticleRequest {
    #[serde(rename = "article_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub article_id: String,
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PublishArticleResponse {
    #[serde(rename = "article_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub article_id: String,
    #[serde(rename = "article_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub article_revision: String,
    #[serde(rename = "body_markdown")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub body_markdown: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "publication_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub publication_revision: String,
    #[serde(rename = "published_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub published_at: String,
    #[serde(rename = "published_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub published_by: String,
    #[serde(rename = "slug")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub slug: String,
    #[serde(rename = "title")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub title: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum PublishArticleError {
    ArticleNotFound,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    RevisionConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SearchPublishedArticlesRequest {
    #[serde(rename = "limit")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub limit: i64,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "query")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub query: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SearchPublishedArticlesResponse {
    #[serde(rename = "articles")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub articles: Vec<SearchPublishedArticlesResponseArticlesItem>,
    #[serde(rename = "index_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub index_revision: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct SearchPublishedArticlesResponseArticlesItem {
    #[serde(rename = "article_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub article_id: String,
    #[serde(rename = "article_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub article_revision: String,
    #[serde(rename = "publication_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub publication_revision: String,
    #[serde(rename = "published_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub published_at: String,
    #[serde(rename = "slug")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub slug: String,
    #[serde(rename = "title")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub title: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum SearchPublishedArticlesError {
    Forbidden,
    InvalidQuery,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct UpdateDraftRequest {
    #[serde(rename = "article_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub article_id: String,
    #[serde(rename = "body_markdown")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub body_markdown: OptionalValue<String>,
    #[serde(rename = "expected_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub expected_revision: String,
    #[serde(rename = "idempotency_key")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub idempotency_key: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "title")]
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_optional_value")]
    pub title: OptionalValue<String>,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct UpdateDraftResponse {
    #[serde(rename = "article_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub article_id: String,
    #[serde(rename = "body_markdown")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub body_markdown: String,
    #[serde(rename = "created_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_at: String,
    #[serde(rename = "created_by")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub created_by: String,
    #[serde(rename = "organization_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub organization_id: String,
    #[serde(rename = "revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub revision: String,
    #[serde(rename = "slug")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub slug: String,
    #[serde(rename = "title")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub title: String,
    #[serde(rename = "updated_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub updated_at: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum UpdateDraftError {
    ArticleNotFound,
    Forbidden,
    IdempotencyConflict,
    InvalidRequest,
    RevisionConflict,
    SlugConflict,
    Unauthenticated,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct KnowledgeBaseCreateDraft;
impl RequestCapability for KnowledgeBaseCreateDraft {
    type Request = CreateDraftRequest;
    type Response = CreateDraftResponse;
    type DomainError = CreateDraftError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CREATE_DRAFT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<KnowledgeBaseRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).create_draft(context, request)
    }
}

#[derive(Debug)]
pub struct KnowledgeBaseGetDraft;
impl RequestCapability for KnowledgeBaseGetDraft {
    type Request = GetDraftRequest;
    type Response = GetDraftResponse;
    type DomainError = GetDraftError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != GET_DRAFT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<KnowledgeBaseRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).get_draft(context, request)
    }
}

#[derive(Debug)]
pub struct KnowledgeBaseGetPublishedArticle;
impl RequestCapability for KnowledgeBaseGetPublishedArticle {
    type Request = GetPublishedArticleRequest;
    type Response = GetPublishedArticleResponse;
    type DomainError = GetPublishedArticleError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != GET_PUBLISHED_ARTICLE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<KnowledgeBaseRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).get_published_article(context, request)
    }
}

#[derive(Debug)]
pub struct KnowledgeBaseListArticles;
impl RequestCapability for KnowledgeBaseListArticles {
    type Request = ListArticlesRequest;
    type Response = ListArticlesResponse;
    type DomainError = ListArticlesError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != LIST_ARTICLES_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<KnowledgeBaseRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).list_articles(context, request)
    }
}

#[derive(Debug)]
pub struct KnowledgeBasePublishArticle;
impl RequestCapability for KnowledgeBasePublishArticle {
    type Request = PublishArticleRequest;
    type Response = PublishArticleResponse;
    type DomainError = PublishArticleError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != PUBLISH_ARTICLE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<KnowledgeBaseRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).publish_article(context, request)
    }
}

#[derive(Debug)]
pub struct KnowledgeBaseSearchPublishedArticles;
impl RequestCapability for KnowledgeBaseSearchPublishedArticles {
    type Request = SearchPublishedArticlesRequest;
    type Response = SearchPublishedArticlesResponse;
    type DomainError = SearchPublishedArticlesError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != SEARCH_PUBLISHED_ARTICLES_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<KnowledgeBaseRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).search_published_articles(context, request)
    }
}

#[derive(Debug)]
pub struct KnowledgeBaseUpdateDraft;
impl RequestCapability for KnowledgeBaseUpdateDraft {
    type Request = UpdateDraftRequest;
    type Response = UpdateDraftResponse;
    type DomainError = UpdateDraftError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != UPDATE_DRAFT_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<KnowledgeBaseRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).update_draft(context, request)
    }
}

impl serde::Serialize for CreateDraftError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::SlugConflict => serializer.serialize_str("slug_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CreateDraftError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "slug_conflict" => Ok(Self::SlugConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for GetDraftError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ArticleNotFound => serializer.serialize_str("article_not_found"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for GetDraftError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "article_not_found" => Ok(Self::ArticleNotFound),
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for GetPublishedArticleError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ArticleNotFound => serializer.serialize_str("article_not_found"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for GetPublishedArticleError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "article_not_found" => Ok(Self::ArticleNotFound),
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ListArticlesError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ListArticlesError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_request" => Ok(Self::InvalidRequest),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for PublishArticleError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ArticleNotFound => serializer.serialize_str("article_not_found"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for PublishArticleError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "article_not_found" => Ok(Self::ArticleNotFound),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for SearchPublishedArticlesError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidQuery => serializer.serialize_str("invalid_query"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for SearchPublishedArticlesError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_query" => Ok(Self::InvalidQuery),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for UpdateDraftError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::ArticleNotFound => serializer.serialize_str("article_not_found"),
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidRequest => serializer.serialize_str("invalid_request"),
            Self::RevisionConflict => serializer.serialize_str("revision_conflict"),
            Self::SlugConflict => serializer.serialize_str("slug_conflict"),
            Self::Unauthenticated => serializer.serialize_str("unauthenticated"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for UpdateDraftError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "article_not_found" => Ok(Self::ArticleNotFound),
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_request" => Ok(Self::InvalidRequest),
                "revision_conflict" => Ok(Self::RevisionConflict),
                "slug_conflict" => Ok(Self::SlugConflict),
                "unauthenticated" => Ok(Self::Unauthenticated),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_create_draft_request(value: &CreateDraftRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_draft_request(wire: &str) -> Result<CreateDraftRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_create_draft_response(value: &CreateDraftResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_draft_response(wire: &str) -> Result<CreateDraftResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_create_draft_error(value: &CreateDraftError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_create_draft_error(wire: &str) -> Result<CreateDraftError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_get_draft_request(value: &GetDraftRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_draft_request(wire: &str) -> Result<GetDraftRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_draft_response(value: &GetDraftResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_draft_response(wire: &str) -> Result<GetDraftResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_draft_error(value: &GetDraftError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_draft_error(wire: &str) -> Result<GetDraftError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_get_published_article_request(value: &GetPublishedArticleRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_published_article_request(wire: &str) -> Result<GetPublishedArticleRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_published_article_response(value: &GetPublishedArticleResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_published_article_response(wire: &str) -> Result<GetPublishedArticleResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_get_published_article_error(value: &GetPublishedArticleError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_get_published_article_error(wire: &str) -> Result<GetPublishedArticleError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_list_articles_request(value: &ListArticlesRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_articles_request(wire: &str) -> Result<ListArticlesRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_articles_response(value: &ListArticlesResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_articles_response(wire: &str) -> Result<ListArticlesResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_list_articles_error(value: &ListArticlesError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_list_articles_error(wire: &str) -> Result<ListArticlesError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_publish_article_request(value: &PublishArticleRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_publish_article_request(wire: &str) -> Result<PublishArticleRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_publish_article_response(value: &PublishArticleResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_publish_article_response(wire: &str) -> Result<PublishArticleResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_publish_article_error(value: &PublishArticleError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_publish_article_error(wire: &str) -> Result<PublishArticleError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_search_published_articles_request(value: &SearchPublishedArticlesRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_search_published_articles_request(wire: &str) -> Result<SearchPublishedArticlesRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_search_published_articles_response(value: &SearchPublishedArticlesResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_search_published_articles_response(wire: &str) -> Result<SearchPublishedArticlesResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_search_published_articles_error(value: &SearchPublishedArticlesError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_search_published_articles_error(wire: &str) -> Result<SearchPublishedArticlesError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_update_draft_request(value: &UpdateDraftRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_update_draft_request(wire: &str) -> Result<UpdateDraftRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_update_draft_response(value: &UpdateDraftResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_update_draft_response(wire: &str) -> Result<UpdateDraftResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_update_draft_error(value: &UpdateDraftError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_update_draft_error(wire: &str) -> Result<UpdateDraftError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoKnowledgeBaseCreateDraftResult {
    fn __lenso_into_result(self) -> Result<Result<CreateDraftResponse, CreateDraftError>, RuntimeFailure>;
}
impl __LensoIntoKnowledgeBaseCreateDraftResult for Result<CreateDraftResponse, CreateDraftError> {
    fn __lenso_into_result(self) -> Result<Result<CreateDraftResponse, CreateDraftError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoKnowledgeBaseCreateDraftResult for Result<Result<CreateDraftResponse, CreateDraftError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<CreateDraftResponse, CreateDraftError>, RuntimeFailure> { self }
}
impl __LensoIntoKnowledgeBaseCreateDraftResult for Result<CreateDraftResponse, lenso_plugin_authoring::PluginError<CreateDraftError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<CreateDraftResponse, CreateDraftError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoKnowledgeBaseCreateDraftResult for Result<CreateDraftResponse, KnowledgeBaseCreateDraftInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<CreateDraftResponse, CreateDraftError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(KnowledgeBaseCreateDraftInvocationError::Domain(error)) => Ok(Err(error)),
            Err(KnowledgeBaseCreateDraftInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoKnowledgeBaseGetDraftResult {
    fn __lenso_into_result(self) -> Result<Result<GetDraftResponse, GetDraftError>, RuntimeFailure>;
}
impl __LensoIntoKnowledgeBaseGetDraftResult for Result<GetDraftResponse, GetDraftError> {
    fn __lenso_into_result(self) -> Result<Result<GetDraftResponse, GetDraftError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoKnowledgeBaseGetDraftResult for Result<Result<GetDraftResponse, GetDraftError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<GetDraftResponse, GetDraftError>, RuntimeFailure> { self }
}
impl __LensoIntoKnowledgeBaseGetDraftResult for Result<GetDraftResponse, lenso_plugin_authoring::PluginError<GetDraftError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<GetDraftResponse, GetDraftError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoKnowledgeBaseGetDraftResult for Result<GetDraftResponse, KnowledgeBaseGetDraftInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<GetDraftResponse, GetDraftError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(KnowledgeBaseGetDraftInvocationError::Domain(error)) => Ok(Err(error)),
            Err(KnowledgeBaseGetDraftInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoKnowledgeBaseGetPublishedArticleResult {
    fn __lenso_into_result(self) -> Result<Result<GetPublishedArticleResponse, GetPublishedArticleError>, RuntimeFailure>;
}
impl __LensoIntoKnowledgeBaseGetPublishedArticleResult for Result<GetPublishedArticleResponse, GetPublishedArticleError> {
    fn __lenso_into_result(self) -> Result<Result<GetPublishedArticleResponse, GetPublishedArticleError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoKnowledgeBaseGetPublishedArticleResult for Result<Result<GetPublishedArticleResponse, GetPublishedArticleError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<GetPublishedArticleResponse, GetPublishedArticleError>, RuntimeFailure> { self }
}
impl __LensoIntoKnowledgeBaseGetPublishedArticleResult for Result<GetPublishedArticleResponse, lenso_plugin_authoring::PluginError<GetPublishedArticleError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<GetPublishedArticleResponse, GetPublishedArticleError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoKnowledgeBaseGetPublishedArticleResult for Result<GetPublishedArticleResponse, KnowledgeBaseGetPublishedArticleInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<GetPublishedArticleResponse, GetPublishedArticleError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(KnowledgeBaseGetPublishedArticleInvocationError::Domain(error)) => Ok(Err(error)),
            Err(KnowledgeBaseGetPublishedArticleInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoKnowledgeBaseListArticlesResult {
    fn __lenso_into_result(self) -> Result<Result<ListArticlesResponse, ListArticlesError>, RuntimeFailure>;
}
impl __LensoIntoKnowledgeBaseListArticlesResult for Result<ListArticlesResponse, ListArticlesError> {
    fn __lenso_into_result(self) -> Result<Result<ListArticlesResponse, ListArticlesError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoKnowledgeBaseListArticlesResult for Result<Result<ListArticlesResponse, ListArticlesError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ListArticlesResponse, ListArticlesError>, RuntimeFailure> { self }
}
impl __LensoIntoKnowledgeBaseListArticlesResult for Result<ListArticlesResponse, lenso_plugin_authoring::PluginError<ListArticlesError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ListArticlesResponse, ListArticlesError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoKnowledgeBaseListArticlesResult for Result<ListArticlesResponse, KnowledgeBaseListArticlesInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ListArticlesResponse, ListArticlesError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(KnowledgeBaseListArticlesInvocationError::Domain(error)) => Ok(Err(error)),
            Err(KnowledgeBaseListArticlesInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoKnowledgeBasePublishArticleResult {
    fn __lenso_into_result(self) -> Result<Result<PublishArticleResponse, PublishArticleError>, RuntimeFailure>;
}
impl __LensoIntoKnowledgeBasePublishArticleResult for Result<PublishArticleResponse, PublishArticleError> {
    fn __lenso_into_result(self) -> Result<Result<PublishArticleResponse, PublishArticleError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoKnowledgeBasePublishArticleResult for Result<Result<PublishArticleResponse, PublishArticleError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<PublishArticleResponse, PublishArticleError>, RuntimeFailure> { self }
}
impl __LensoIntoKnowledgeBasePublishArticleResult for Result<PublishArticleResponse, lenso_plugin_authoring::PluginError<PublishArticleError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<PublishArticleResponse, PublishArticleError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoKnowledgeBasePublishArticleResult for Result<PublishArticleResponse, KnowledgeBasePublishArticleInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<PublishArticleResponse, PublishArticleError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(KnowledgeBasePublishArticleInvocationError::Domain(error)) => Ok(Err(error)),
            Err(KnowledgeBasePublishArticleInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoKnowledgeBaseSearchPublishedArticlesResult {
    fn __lenso_into_result(self) -> Result<Result<SearchPublishedArticlesResponse, SearchPublishedArticlesError>, RuntimeFailure>;
}
impl __LensoIntoKnowledgeBaseSearchPublishedArticlesResult for Result<SearchPublishedArticlesResponse, SearchPublishedArticlesError> {
    fn __lenso_into_result(self) -> Result<Result<SearchPublishedArticlesResponse, SearchPublishedArticlesError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoKnowledgeBaseSearchPublishedArticlesResult for Result<Result<SearchPublishedArticlesResponse, SearchPublishedArticlesError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<SearchPublishedArticlesResponse, SearchPublishedArticlesError>, RuntimeFailure> { self }
}
impl __LensoIntoKnowledgeBaseSearchPublishedArticlesResult for Result<SearchPublishedArticlesResponse, lenso_plugin_authoring::PluginError<SearchPublishedArticlesError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<SearchPublishedArticlesResponse, SearchPublishedArticlesError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoKnowledgeBaseSearchPublishedArticlesResult for Result<SearchPublishedArticlesResponse, KnowledgeBaseSearchPublishedArticlesInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<SearchPublishedArticlesResponse, SearchPublishedArticlesError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(KnowledgeBaseSearchPublishedArticlesInvocationError::Domain(error)) => Ok(Err(error)),
            Err(KnowledgeBaseSearchPublishedArticlesInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoKnowledgeBaseUpdateDraftResult {
    fn __lenso_into_result(self) -> Result<Result<UpdateDraftResponse, UpdateDraftError>, RuntimeFailure>;
}
impl __LensoIntoKnowledgeBaseUpdateDraftResult for Result<UpdateDraftResponse, UpdateDraftError> {
    fn __lenso_into_result(self) -> Result<Result<UpdateDraftResponse, UpdateDraftError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoKnowledgeBaseUpdateDraftResult for Result<Result<UpdateDraftResponse, UpdateDraftError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<UpdateDraftResponse, UpdateDraftError>, RuntimeFailure> { self }
}
impl __LensoIntoKnowledgeBaseUpdateDraftResult for Result<UpdateDraftResponse, lenso_plugin_authoring::PluginError<UpdateDraftError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<UpdateDraftResponse, UpdateDraftError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoKnowledgeBaseUpdateDraftResult for Result<UpdateDraftResponse, KnowledgeBaseUpdateDraftInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<UpdateDraftResponse, UpdateDraftError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(KnowledgeBaseUpdateDraftInvocationError::Domain(error)) => Ok(Err(error)),
            Err(KnowledgeBaseUpdateDraftInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait KnowledgeBaseProvider: fmt::Debug + 'static {
    fn create_draft(&self, context: InvocationContext, request: CreateDraftRequest) -> NativeRequestFuture<KnowledgeBaseCreateDraft>;
    fn get_draft(&self, context: InvocationContext, request: GetDraftRequest) -> NativeRequestFuture<KnowledgeBaseGetDraft>;
    fn get_published_article(&self, context: InvocationContext, request: GetPublishedArticleRequest) -> NativeRequestFuture<KnowledgeBaseGetPublishedArticle>;
    fn list_articles(&self, context: InvocationContext, request: ListArticlesRequest) -> NativeRequestFuture<KnowledgeBaseListArticles>;
    fn publish_article(&self, context: InvocationContext, request: PublishArticleRequest) -> NativeRequestFuture<KnowledgeBasePublishArticle>;
    fn search_published_articles(&self, context: InvocationContext, request: SearchPublishedArticlesRequest) -> NativeRequestFuture<KnowledgeBaseSearchPublishedArticles>;
    fn update_draft(&self, context: InvocationContext, request: UpdateDraftRequest) -> NativeRequestFuture<KnowledgeBaseUpdateDraft>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_knowledge_base {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportKnowledgeBase;
        impl $crate::KnowledgeBaseProvider for $plugin {
        fn create_draft(&self, context: __LensoNativeSupportKnowledgeBase::InvocationContext, request: $crate::CreateDraftRequest) -> __LensoNativeSupportKnowledgeBase::NativeRequestFuture<$crate::KnowledgeBaseCreateDraft> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::create_draft(&plugin, context, request).await;
                $crate::__LensoIntoKnowledgeBaseCreateDraftResult::__lenso_into_result(result)
            })
        }
        fn get_draft(&self, context: __LensoNativeSupportKnowledgeBase::InvocationContext, request: $crate::GetDraftRequest) -> __LensoNativeSupportKnowledgeBase::NativeRequestFuture<$crate::KnowledgeBaseGetDraft> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::get_draft(&plugin, context, request).await;
                $crate::__LensoIntoKnowledgeBaseGetDraftResult::__lenso_into_result(result)
            })
        }
        fn get_published_article(&self, context: __LensoNativeSupportKnowledgeBase::InvocationContext, request: $crate::GetPublishedArticleRequest) -> __LensoNativeSupportKnowledgeBase::NativeRequestFuture<$crate::KnowledgeBaseGetPublishedArticle> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::get_published_article(&plugin, context, request).await;
                $crate::__LensoIntoKnowledgeBaseGetPublishedArticleResult::__lenso_into_result(result)
            })
        }
        fn list_articles(&self, context: __LensoNativeSupportKnowledgeBase::InvocationContext, request: $crate::ListArticlesRequest) -> __LensoNativeSupportKnowledgeBase::NativeRequestFuture<$crate::KnowledgeBaseListArticles> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::list_articles(&plugin, context, request).await;
                $crate::__LensoIntoKnowledgeBaseListArticlesResult::__lenso_into_result(result)
            })
        }
        fn publish_article(&self, context: __LensoNativeSupportKnowledgeBase::InvocationContext, request: $crate::PublishArticleRequest) -> __LensoNativeSupportKnowledgeBase::NativeRequestFuture<$crate::KnowledgeBasePublishArticle> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::publish_article(&plugin, context, request).await;
                $crate::__LensoIntoKnowledgeBasePublishArticleResult::__lenso_into_result(result)
            })
        }
        fn search_published_articles(&self, context: __LensoNativeSupportKnowledgeBase::InvocationContext, request: $crate::SearchPublishedArticlesRequest) -> __LensoNativeSupportKnowledgeBase::NativeRequestFuture<$crate::KnowledgeBaseSearchPublishedArticles> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::search_published_articles(&plugin, context, request).await;
                $crate::__LensoIntoKnowledgeBaseSearchPublishedArticlesResult::__lenso_into_result(result)
            })
        }
        fn update_draft(&self, context: __LensoNativeSupportKnowledgeBase::InvocationContext, request: $crate::UpdateDraftRequest) -> __LensoNativeSupportKnowledgeBase::NativeRequestFuture<$crate::KnowledgeBaseUpdateDraft> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::update_draft(&plugin, context, request).await;
                $crate::__LensoIntoKnowledgeBaseUpdateDraftResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct KnowledgeBaseRequestEndpoint { provider: Rc<dyn KnowledgeBaseProvider> }

#[derive(Debug)]
pub struct KnowledgeBaseEndpoint<P: KnowledgeBaseProvider> { provider: Rc<P>, request_endpoint: KnowledgeBaseRequestEndpoint }
impl<P: KnowledgeBaseProvider> KnowledgeBaseEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn KnowledgeBaseProvider> = provider.clone();
        Self { provider, request_endpoint: KnowledgeBaseRequestEndpoint { provider: request_provider } }
    }
}

impl<P: KnowledgeBaseProvider> NativeRequestEndpoint for KnowledgeBaseEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        CREATE_DRAFT_OPERATION,
        GET_DRAFT_OPERATION,
        GET_PUBLISHED_ARTICLE_OPERATION,
        LIST_ARTICLES_OPERATION,
        PUBLISH_ARTICLE_OPERATION,
        SEARCH_PUBLISHED_ARTICLES_OPERATION,
        UPDATE_DRAFT_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            CREATE_DRAFT_OPERATION => {
                let Ok(request) = request.downcast::<CreateDraftRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).create_draft(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            GET_DRAFT_OPERATION => {
                let Ok(request) = request.downcast::<GetDraftRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).get_draft(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            GET_PUBLISHED_ARTICLE_OPERATION => {
                let Ok(request) = request.downcast::<GetPublishedArticleRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).get_published_article(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            LIST_ARTICLES_OPERATION => {
                let Ok(request) = request.downcast::<ListArticlesRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).list_articles(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            PUBLISH_ARTICLE_OPERATION => {
                let Ok(request) = request.downcast::<PublishArticleRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).publish_article(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            SEARCH_PUBLISHED_ARTICLES_OPERATION => {
                let Ok(request) = request.downcast::<SearchPublishedArticlesRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).search_published_articles(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            UPDATE_DRAFT_OPERATION => {
                let Ok(request) = request.downcast::<UpdateDraftRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).update_draft(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_knowledge_base {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::KnowledgeBaseEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_knowledge_base {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_knowledge_base!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct KnowledgeBaseClient {
    create_draft: NativeRequestHandle<KnowledgeBaseCreateDraft>,
    get_draft: NativeRequestHandle<KnowledgeBaseGetDraft>,
    get_published_article: NativeRequestHandle<KnowledgeBaseGetPublishedArticle>,
    list_articles: NativeRequestHandle<KnowledgeBaseListArticles>,
    publish_article: NativeRequestHandle<KnowledgeBasePublishArticle>,
    search_published_articles: NativeRequestHandle<KnowledgeBaseSearchPublishedArticles>,
    update_draft: NativeRequestHandle<KnowledgeBaseUpdateDraft>,
}
impl KnowledgeBaseClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn create_draft(&self, request: CreateDraftRequest) -> Result<CreateDraftResponse, KnowledgeBaseCreateDraftInvocationError> {
        self.create_draft.invoke(CREATE_DRAFT_OPERATION, request).await
            .map_err(KnowledgeBaseCreateDraftInvocationError::Runtime)?
            .map_err(KnowledgeBaseCreateDraftInvocationError::Domain)
    }

    pub async fn create_draft_with_context(&self, context: InvocationContext, request: CreateDraftRequest) -> Result<CreateDraftResponse, KnowledgeBaseCreateDraftInvocationError> {
        self.create_draft.invoke_with_context(CREATE_DRAFT_OPERATION, context, request).await
            .map_err(KnowledgeBaseCreateDraftInvocationError::Runtime)?
            .map_err(KnowledgeBaseCreateDraftInvocationError::Domain)
    }

    pub async fn get_draft(&self, request: GetDraftRequest) -> Result<GetDraftResponse, KnowledgeBaseGetDraftInvocationError> {
        self.get_draft.invoke(GET_DRAFT_OPERATION, request).await
            .map_err(KnowledgeBaseGetDraftInvocationError::Runtime)?
            .map_err(KnowledgeBaseGetDraftInvocationError::Domain)
    }

    pub async fn get_draft_with_context(&self, context: InvocationContext, request: GetDraftRequest) -> Result<GetDraftResponse, KnowledgeBaseGetDraftInvocationError> {
        self.get_draft.invoke_with_context(GET_DRAFT_OPERATION, context, request).await
            .map_err(KnowledgeBaseGetDraftInvocationError::Runtime)?
            .map_err(KnowledgeBaseGetDraftInvocationError::Domain)
    }

    pub async fn get_published_article(&self, request: GetPublishedArticleRequest) -> Result<GetPublishedArticleResponse, KnowledgeBaseGetPublishedArticleInvocationError> {
        self.get_published_article.invoke(GET_PUBLISHED_ARTICLE_OPERATION, request).await
            .map_err(KnowledgeBaseGetPublishedArticleInvocationError::Runtime)?
            .map_err(KnowledgeBaseGetPublishedArticleInvocationError::Domain)
    }

    pub async fn get_published_article_with_context(&self, context: InvocationContext, request: GetPublishedArticleRequest) -> Result<GetPublishedArticleResponse, KnowledgeBaseGetPublishedArticleInvocationError> {
        self.get_published_article.invoke_with_context(GET_PUBLISHED_ARTICLE_OPERATION, context, request).await
            .map_err(KnowledgeBaseGetPublishedArticleInvocationError::Runtime)?
            .map_err(KnowledgeBaseGetPublishedArticleInvocationError::Domain)
    }

    pub async fn list_articles(&self, request: ListArticlesRequest) -> Result<ListArticlesResponse, KnowledgeBaseListArticlesInvocationError> {
        self.list_articles.invoke(LIST_ARTICLES_OPERATION, request).await
            .map_err(KnowledgeBaseListArticlesInvocationError::Runtime)?
            .map_err(KnowledgeBaseListArticlesInvocationError::Domain)
    }

    pub async fn list_articles_with_context(&self, context: InvocationContext, request: ListArticlesRequest) -> Result<ListArticlesResponse, KnowledgeBaseListArticlesInvocationError> {
        self.list_articles.invoke_with_context(LIST_ARTICLES_OPERATION, context, request).await
            .map_err(KnowledgeBaseListArticlesInvocationError::Runtime)?
            .map_err(KnowledgeBaseListArticlesInvocationError::Domain)
    }

    pub async fn publish_article(&self, request: PublishArticleRequest) -> Result<PublishArticleResponse, KnowledgeBasePublishArticleInvocationError> {
        self.publish_article.invoke(PUBLISH_ARTICLE_OPERATION, request).await
            .map_err(KnowledgeBasePublishArticleInvocationError::Runtime)?
            .map_err(KnowledgeBasePublishArticleInvocationError::Domain)
    }

    pub async fn publish_article_with_context(&self, context: InvocationContext, request: PublishArticleRequest) -> Result<PublishArticleResponse, KnowledgeBasePublishArticleInvocationError> {
        self.publish_article.invoke_with_context(PUBLISH_ARTICLE_OPERATION, context, request).await
            .map_err(KnowledgeBasePublishArticleInvocationError::Runtime)?
            .map_err(KnowledgeBasePublishArticleInvocationError::Domain)
    }

    pub async fn search_published_articles(&self, request: SearchPublishedArticlesRequest) -> Result<SearchPublishedArticlesResponse, KnowledgeBaseSearchPublishedArticlesInvocationError> {
        self.search_published_articles.invoke(SEARCH_PUBLISHED_ARTICLES_OPERATION, request).await
            .map_err(KnowledgeBaseSearchPublishedArticlesInvocationError::Runtime)?
            .map_err(KnowledgeBaseSearchPublishedArticlesInvocationError::Domain)
    }

    pub async fn search_published_articles_with_context(&self, context: InvocationContext, request: SearchPublishedArticlesRequest) -> Result<SearchPublishedArticlesResponse, KnowledgeBaseSearchPublishedArticlesInvocationError> {
        self.search_published_articles.invoke_with_context(SEARCH_PUBLISHED_ARTICLES_OPERATION, context, request).await
            .map_err(KnowledgeBaseSearchPublishedArticlesInvocationError::Runtime)?
            .map_err(KnowledgeBaseSearchPublishedArticlesInvocationError::Domain)
    }

    pub async fn update_draft(&self, request: UpdateDraftRequest) -> Result<UpdateDraftResponse, KnowledgeBaseUpdateDraftInvocationError> {
        self.update_draft.invoke(UPDATE_DRAFT_OPERATION, request).await
            .map_err(KnowledgeBaseUpdateDraftInvocationError::Runtime)?
            .map_err(KnowledgeBaseUpdateDraftInvocationError::Domain)
    }

    pub async fn update_draft_with_context(&self, context: InvocationContext, request: UpdateDraftRequest) -> Result<UpdateDraftResponse, KnowledgeBaseUpdateDraftInvocationError> {
        self.update_draft.invoke_with_context(UPDATE_DRAFT_OPERATION, context, request).await
            .map_err(KnowledgeBaseUpdateDraftInvocationError::Runtime)?
            .map_err(KnowledgeBaseUpdateDraftInvocationError::Domain)
    }
}

impl CapabilityClient for KnowledgeBaseClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            create_draft: dependencies.one::<KnowledgeBaseCreateDraft>()?,
            get_draft: dependencies.one::<KnowledgeBaseGetDraft>()?,
            get_published_article: dependencies.one::<KnowledgeBaseGetPublishedArticle>()?,
            list_articles: dependencies.one::<KnowledgeBaseListArticles>()?,
            publish_article: dependencies.one::<KnowledgeBasePublishArticle>()?,
            search_published_articles: dependencies.one::<KnowledgeBaseSearchPublishedArticles>()?,
            update_draft: dependencies.one::<KnowledgeBaseUpdateDraft>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for KnowledgeBaseClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    create_draft: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<KnowledgeBaseCreateDraft>()?,
                    get_draft: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<KnowledgeBaseGetDraft>()?,
                    get_published_article: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<KnowledgeBaseGetPublishedArticle>()?,
                    list_articles: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<KnowledgeBaseListArticles>()?,
                    publish_article: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<KnowledgeBasePublishArticle>()?,
                    search_published_articles: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<KnowledgeBaseSearchPublishedArticles>()?,
                    update_draft: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<KnowledgeBaseUpdateDraft>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum KnowledgeBaseCreateDraftInvocationError {
    Domain(CreateDraftError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum KnowledgeBaseGetDraftInvocationError {
    Domain(GetDraftError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum KnowledgeBaseGetPublishedArticleInvocationError {
    Domain(GetPublishedArticleError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum KnowledgeBaseListArticlesInvocationError {
    Domain(ListArticlesError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum KnowledgeBasePublishArticleInvocationError {
    Domain(PublishArticleError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum KnowledgeBaseSearchPublishedArticlesInvocationError {
    Domain(SearchPublishedArticlesError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum KnowledgeBaseUpdateDraftInvocationError {
    Domain(UpdateDraftError),
    Runtime(RuntimeFailure),
}
